create table if not exists public.player_identities (
  id uuid primary key default gen_random_uuid(),
  csp_number bigint generated by default as identity unique not null,
  display_name text not null check (length(btrim(display_name)) between 1 and 160),
  normalized_name text not null,
  claimed_profile_id uuid unique references public.profiles(id) on delete set null,
  status text not null default 'unclaimed' check (status in ('unclaimed','claimed','merged')),
  created_source text not null default 'manual',
  created_by uuid references public.profiles(id) on delete set null,
  merged_into_id uuid references public.player_identities(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists player_identities_normalized_name_idx on public.player_identities(normalized_name) where status <> 'merged';
create index if not exists player_identities_claimed_profile_idx on public.player_identities(claimed_profile_id) where claimed_profile_id is not null;

alter table public.player_identities enable row level security;

drop policy if exists player_identities_authenticated_read on public.player_identities;
create policy player_identities_authenticated_read on public.player_identities
for select to authenticated
using (status <> 'merged');

create or replace function public.normalize_player_identity_name(p_name text)
returns text
language sql
immutable
set search_path=''
as $$
  select lower(regexp_replace(btrim(coalesce(p_name,'')), '\s+', ' ', 'g'));
$$;

create or replace function public.format_csp_player_id(p_number bigint)
returns text
language sql
immutable
set search_path=''
as $$
  select lpad(coalesce(p_number,0)::text, 6, '0');
$$;

create or replace function public.resolve_or_create_player_identity(
  p_display_name text,
  p_profile_id uuid default null,
  p_source text default 'manual'
)
returns public.player_identities
language plpgsql
security definer
set search_path='public','pg_temp'
as $$
declare
  v_name text;
  v_norm text;
  v_identity public.player_identities;
  v_count int;
begin
  if auth.uid() is null then
    raise exception 'AUTHENTICATION_REQUIRED';
  end if;

  v_name := regexp_replace(btrim(coalesce(p_display_name,'')), '\s+', ' ', 'g');
  if length(v_name) < 1 then raise exception 'PLAYER_NAME_REQUIRED'; end if;
  if length(v_name) > 160 then raise exception 'PLAYER_NAME_TOO_LONG'; end if;
  v_norm := public.normalize_player_identity_name(v_name);

  if p_profile_id is not null then
    select * into v_identity
    from public.player_identities
    where claimed_profile_id=p_profile_id and status<>'merged'
    limit 1;

    if v_identity.id is not null then
      update public.player_identities
      set display_name=case when nullif(v_name,'') is not null then v_name else display_name end,
          normalized_name=case when nullif(v_norm,'') is not null then v_norm else normalized_name end,
          status='claimed',
          updated_at=now()
      where id=v_identity.id
      returning * into v_identity;
      return v_identity;
    end if;

    insert into public.player_identities(display_name,normalized_name,claimed_profile_id,status,created_source,created_by)
    values(v_name,v_norm,p_profile_id,'claimed',coalesce(nullif(btrim(p_source),''),'manual'),auth.uid())
    returning * into v_identity;
    return v_identity;
  end if;

  select count(*) into v_count
  from public.player_identities
  where normalized_name=v_norm and status<>'merged';

  if v_count=1 then
    select * into v_identity
    from public.player_identities
    where normalized_name=v_norm and status<>'merged'
    limit 1;
    return v_identity;
  end if;

  insert into public.player_identities(display_name,normalized_name,status,created_source,created_by)
  values(v_name,v_norm,'unclaimed',coalesce(nullif(btrim(p_source),''),'manual'),auth.uid())
  returning * into v_identity;
  return v_identity;
end;
$$;

grant execute on function public.resolve_or_create_player_identity(text,uuid,text) to authenticated;
grant execute on function public.format_csp_player_id(bigint) to anon,authenticated;

alter table public.training_session_participants
  add column if not exists player_identity_id uuid references public.player_identities(id) on delete set null;
create index if not exists training_session_participants_identity_idx on public.training_session_participants(player_identity_id);

alter table public.tournament_players
  add column if not exists player_identity_id uuid references public.player_identities(id) on delete set null;
create index if not exists tournament_players_identity_idx on public.tournament_players(player_identity_id);

alter table public.score_events
  add column if not exists player_identity_id uuid references public.player_identities(id) on delete set null;
create index if not exists score_events_identity_idx on public.score_events(player_identity_id);

create or replace function public.set_training_participant_identity()
returns trigger
language plpgsql
security definer
set search_path='public','pg_temp'
as $$
declare v public.player_identities;
begin
  if new.player_identity_id is not null then return new; end if;
  v := public.resolve_or_create_player_identity(new.display_name,new.player_id,'training_scoreboard');
  new.player_identity_id := v.id;
  return new;
end;
$$;

drop trigger if exists trg_training_participant_identity on public.training_session_participants;
create trigger trg_training_participant_identity
before insert or update of display_name,player_id,player_identity_id
on public.training_session_participants
for each row execute function public.set_training_participant_identity();

create or replace function public.set_tournament_player_identity()
returns trigger
language plpgsql
security definer
set search_path='public','pg_temp'
as $$
declare v public.player_identities;
begin
  if new.player_identity_id is not null then return new; end if;
  v := public.resolve_or_create_player_identity(new.name,new.user_id,'tournament');
  new.player_identity_id := v.id;
  return new;
end;
$$;

drop trigger if exists trg_tournament_player_identity on public.tournament_players;
create trigger trg_tournament_player_identity
before insert or update of name,user_id,player_identity_id
on public.tournament_players
for each row execute function public.set_tournament_player_identity();

create or replace function public.set_score_event_identity()
returns trigger
language plpgsql
security definer
set search_path='public','pg_temp'
as $$
begin
  if new.player_identity_id is not null then return new; end if;

  if new.training_participant_id is not null then
    select player_identity_id into new.player_identity_id
    from public.training_session_participants
    where id=new.training_participant_id;
  elsif new.tournament_player_id is not null then
    select player_identity_id into new.player_identity_id
    from public.tournament_players
    where id=new.tournament_player_id;
  elsif new.player_profile_id is not null then
    select id into new.player_identity_id
    from public.player_identities
    where claimed_profile_id=new.player_profile_id and status<>'merged'
    limit 1;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_score_event_identity on public.score_events;
create trigger trg_score_event_identity
before insert or update of training_participant_id,tournament_player_id,player_profile_id,player_identity_id
on public.score_events
for each row execute function public.set_score_event_identity();

create or replace function public.sync_profile_player_identity()
returns trigger
language plpgsql
security definer
set search_path='public','pg_temp'
as $$
declare v_name text; v_norm text;
begin
  if new.role::text not in ('player','admin') then return new; end if;
  v_name := regexp_replace(btrim(coalesce(new.full_name,split_part(coalesce(new.email,''),'@',1),'Hráč')), '\s+', ' ', 'g');
  v_norm := public.normalize_player_identity_name(v_name);

  insert into public.player_identities(display_name,normalized_name,claimed_profile_id,status,created_source,created_by)
  values(v_name,v_norm,new.id,'claimed','account',new.id)
  on conflict (claimed_profile_id) do update
    set display_name=excluded.display_name,
        normalized_name=excluded.normalized_name,
        status='claimed',
        updated_at=now();
  return new;
end;
$$;

drop trigger if exists trg_profile_player_identity on public.profiles;
create trigger trg_profile_player_identity
after insert or update of full_name,email,role
on public.profiles
for each row execute function public.sync_profile_player_identity();

insert into public.player_identities(display_name,normalized_name,claimed_profile_id,status,created_source,created_by)
select regexp_replace(btrim(coalesce(p.full_name,split_part(coalesce(p.email,''),'@',1),'Hráč')), '\s+', ' ', 'g'),
       public.normalize_player_identity_name(coalesce(p.full_name,split_part(coalesce(p.email,''),'@',1),'Hráč')),
       p.id,'claimed','account_backfill',p.id
from public.profiles p
where p.role::text in ('player','admin')
on conflict (claimed_profile_id) do nothing;

update public.training_session_participants tsp
set player_identity_id=pi.id
from public.player_identities pi
where tsp.player_identity_id is null
  and tsp.player_id is not null
  and pi.claimed_profile_id=tsp.player_id;

update public.tournament_players tp
set player_identity_id=pi.id
from public.player_identities pi
where tp.player_identity_id is null
  and tp.user_id is not null
  and pi.claimed_profile_id=tp.user_id;

-- Name-only historical rows: reuse only when the name maps to exactly one active identity.
with unique_names as (
  select normalized_name,min(id::text)::uuid as identity_id
  from public.player_identities
  where status<>'merged'
  group by normalized_name
  having count(*)=1
)
update public.training_session_participants tsp
set player_identity_id=u.identity_id
from unique_names u
where tsp.player_identity_id is null
  and public.normalize_player_identity_name(tsp.display_name)=u.normalized_name;

with unique_names as (
  select normalized_name,min(id::text)::uuid as identity_id
  from public.player_identities
  where status<>'merged'
  group by normalized_name
  having count(*)=1
)
update public.tournament_players tp
set player_identity_id=u.identity_id
from unique_names u
where tp.player_identity_id is null
  and public.normalize_player_identity_name(tp.name)=u.normalized_name;

update public.score_events se
set player_identity_id=tsp.player_identity_id
from public.training_session_participants tsp
where se.player_identity_id is null and se.training_participant_id=tsp.id and tsp.player_identity_id is not null;

update public.score_events se
set player_identity_id=tp.player_identity_id
from public.tournament_players tp
where se.player_identity_id is null and se.tournament_player_id=tp.id and tp.player_identity_id is not null;

