-- CSP views, phase transition and shot clock
create or replace function public.complete_round_robin_phase(p_phase_id uuid,p_qualifiers jsonb,p_next_phase_type text) returns public.tournament_phases language plpgsql security definer set search_path=public,pg_temp as $$ declare ph public.tournament_phases; nextph public.tournament_phases; item jsonb; begin select p.* into ph from public.tournament_phases p join public.tournaments t on t.id=p.tournament_id where p.id=p_phase_id and p.phase_type='rr' and (t.owner_id=auth.uid() or public.is_admin(auth.uid())); if ph.id is null then raise exception 'Round Robin phase not found or access denied'; end if; if exists(select 1 from public.matches where phase_id=p_phase_id and status not in('completed','forfeited')) then raise exception 'Phase has unfinished matches'; end if; delete from public.phase_qualifiers where phase_id=p_phase_id; for item in select * from jsonb_array_elements(p_qualifiers) loop insert into public.phase_qualifiers(phase_id,tournament_player_id,source_group,source_position,seed) values(p_phase_id,(item->>'tournament_player_id')::uuid,(item->>'source_group')::int,(item->>'source_position')::int,(item->>'seed')::int); end loop; update public.tournament_phases set status='completed',completed_at=now() where id=p_phase_id; insert into public.tournament_phases(tournament_id,phase_number,phase_type,status,started_at,config) values(ph.tournament_id,ph.phase_number+1,p_next_phase_type,'active',now(),jsonb_build_object('source_phase_id',p_phase_id)) returning * into nextph; update public.tournaments set current_phase_id=nextph.id where id=ph.tournament_id; insert into public.audit_logs(user_id,entity_type,entity_id,action,metadata) values(auth.uid(),'tournament_phase',p_phase_id,'completed',jsonb_build_object('next_phase_id',nextph.id)); return nextph; end $$;

create or replace function public.start_shot_clock(p_match_id uuid,p_player_id uuid,p_post_break boolean default false) returns public.matches language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.matches; begin update public.matches m set shot_clock_started_at=now(),shot_clock_current_player_id=p_player_id,shot_clock_remaining_seconds=case when p_post_break then post_break_seconds else shot_clock_seconds end,shot_clock_paused=false where id=p_match_id and shot_clock_enabled and exists(select 1 from public.tournaments t where t.id=m.tournament_id and (t.owner_id=auth.uid() or public.is_admin(auth.uid()))) returning * into r; if r.id is null then raise exception 'Shot clock unavailable or access denied'; end if; return r; end $$;
create or replace function public.pause_shot_clock(p_match_id uuid) returns public.matches language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.matches; begin update public.matches m set shot_clock_remaining_seconds=greatest(0,coalesce(shot_clock_remaining_seconds,shot_clock_seconds)-case when shot_clock_paused or shot_clock_started_at is null then 0 else extract(epoch from(now()-shot_clock_started_at))::int end),shot_clock_paused=true,shot_clock_started_at=null where id=p_match_id and exists(select 1 from public.tournaments t where t.id=m.tournament_id and (t.owner_id=auth.uid() or public.is_admin(auth.uid()))) returning * into r; return r; end $$;
create or replace function public.use_shot_clock_extension(p_match_id uuid,p_player_id uuid) returns public.matches language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.matches; begin update public.matches m set extensions_used_player1=case when player1_id=p_player_id then extensions_used_player1+1 else extensions_used_player1 end,extensions_used_player2=case when player2_id=p_player_id then extensions_used_player2+1 else extensions_used_player2 end,shot_clock_remaining_seconds=coalesce(shot_clock_remaining_seconds,0)+extension_seconds where id=p_match_id and ((player1_id=p_player_id and extensions_used_player1<extensions_allowed) or(player2_id=p_player_id and extensions_used_player2<extensions_allowed)) and exists(select 1 from public.tournaments t where t.id=m.tournament_id and (t.owner_id=auth.uid() or public.is_admin(auth.uid()))) returning * into r; if r.id is null then raise exception 'No extension available'; end if; return r; end $$;

create or replace view public.user_tournament_history with(security_invoker=true) as select tr.user_id,tr.tournament_id,t.name,t.sport,t.discipline,t.format,t.date,t.status,tr.final_position,tr.matches_played,tr.wins,tr.losses,tr.score_for,tr.score_against,tr.created_at from public.tournament_results tr join public.tournaments t on t.id=tr.tournament_id;
create or replace view public.user_sport_statistics with(security_invoker=true) as select user_id,sport,discipline,count(distinct tournament_id)::int tournaments_played,sum(matches_played)::int matches_played,sum(wins)::int wins,sum(losses)::int losses,case when sum(matches_played)>0 then round(100.0*sum(wins)/sum(matches_played),1) else 0 end win_rate,count(*) filter(where final_position=1)::int tournament_wins from public.user_tournament_history group by user_id,sport,discipline;
create or replace view public.player_match_cards with(security_invoker=true) as select tp.user_id,m.id match_id,m.tournament_id,t.name tournament_name,t.sport,t.discipline,t.format,m.round_key,m.status,m.player1_id,m.player2_id,case when tp.id=m.player1_id then p2.name else p1.name end opponent_name,s.name station_name,m.score1,m.score2,m.called_at,m.arrival_deadline_at,m.penalty_1_at,m.penalty_2_at,m.penalty_3_at,m.forfeit_at,m.player1_ready_at,m.player2_ready_at,m.shot_clock_enabled,m.shot_clock_seconds,m.post_break_seconds,m.extensions_allowed,m.extensions_used_player1,m.extensions_used_player2 from public.matches m join public.tournaments t on t.id=m.tournament_id join public.tournament_players tp on tp.id in(m.player1_id,m.player2_id) left join public.tournament_players p1 on p1.id=m.player1_id left join public.tournament_players p2 on p2.id=m.player2_id left join public.stations s on s.id=m.station_id where tp.user_id is not null;
create or replace view public.tournament_payment_summary with(security_invoker=true) as select tp.tournament_id,count(*)::int players,coalesce(sum(pp.entry_fee_amount),0) expected_amount,coalesce(sum(pp.entry_fee_amount) filter(where pp.payment_status='paid'),0) paid_amount,coalesce(sum(pp.entry_fee_amount) filter(where pp.payment_status='unpaid'),0) unpaid_amount,count(*) filter(where pp.payment_status='waived')::int waived_count,count(*) filter(where pp.payment_status='refunded')::int refunded_count from public.tournament_players tp left join public.tournament_player_payments pp on pp.tournament_player_id=tp.id group by tp.tournament_id;

grant select on public.user_tournament_history,public.user_sport_statistics,public.player_match_cards,public.tournament_payment_summary to authenticated;
grant select on public.tournament_payment_summary to anon;
