-- CSP lifecycle RPC and routing
create or replace function public.start_training_session(p_session_id uuid) returns public.training_sessions language plpgsql security definer set search_path=public,pg_temp as $$
declare r public.training_sessions; begin update public.training_sessions set status='active',started_at=coalesce(started_at,now()),paused_at=null,updated_at=now() where id=p_session_id and owner_id=auth.uid() returning * into r; if r.id is null then raise exception 'Training session not found or access denied'; end if; return r; end $$;
create or replace function public.pause_training_session(p_session_id uuid) returns public.training_sessions language plpgsql security definer set search_path=public,pg_temp as $$
declare r public.training_sessions; begin update public.training_sessions set elapsed_seconds=elapsed_seconds+greatest(0,extract(epoch from(now()-started_at))::int),status='paused',paused_at=now(),started_at=null,updated_at=now() where id=p_session_id and owner_id=auth.uid() and status='active' returning * into r; if r.id is null then raise exception 'Active training session not found'; end if; return r; end $$;
create or replace function public.complete_training_session(p_session_id uuid,p_final_score jsonb,p_winner_name text) returns public.training_sessions language plpgsql security definer set search_path=public,pg_temp as $$
declare r public.training_sessions; begin update public.training_sessions set elapsed_seconds=elapsed_seconds+case when status='active' and started_at is not null then greatest(0,extract(epoch from(now()-started_at))::int) else 0 end,duration_seconds=elapsed_seconds+case when status='active' and started_at is not null then greatest(0,extract(epoch from(now()-started_at))::int) else 0 end,final_score=p_final_score,winner_name=p_winner_name,status='completed',completed_at=now(),started_at=null,paused_at=null,updated_at=now() where id=p_session_id and owner_id=auth.uid() returning * into r; if r.id is null then raise exception 'Training session not found or access denied'; end if; insert into public.audit_logs(user_id,entity_type,entity_id,action) values(auth.uid(),'training_session',p_session_id,'completed'); return r; end $$;

create or replace function public.call_match(p_match_id uuid) returns public.matches language plpgsql security definer set search_path=public,pg_temp as $$
declare r public.matches; cfg jsonb; begin select config into cfg from public.tournaments where id=(select tournament_id from public.matches where id=p_match_id) and owner_id=auth.uid(); if cfg is null then raise exception 'Match not found or access denied'; end if; update public.matches set called_at=now(),arrival_deadline_at=now()+make_interval(mins=>coalesce((cfg->>'arrival_grace_minutes')::int,5)),penalty_1_at=now()+make_interval(mins=>coalesce((cfg->>'penalty_1_minutes')::int,6)),penalty_2_at=now()+make_interval(mins=>coalesce((cfg->>'penalty_2_minutes')::int,11)),penalty_3_at=now()+make_interval(mins=>coalesce((cfg->>'penalty_3_minutes')::int,16)),forfeit_at=now()+make_interval(mins=>coalesce((cfg->>'forfeit_minutes')::int,20)),match_call_status='called',status='called' where id=p_match_id returning * into r; insert into public.audit_logs(user_id,entity_type,entity_id,action) values(auth.uid(),'match',p_match_id,'called'); return r; end $$;

create or replace function public.get_match_arrival_status(p_match_id uuid) returns table(match_id uuid,seconds_to_deadline integer,penalty_level integer,suggested_penalty integer,can_forfeit boolean) language sql stable security definer set search_path=public,pg_temp as $$ select m.id,case when m.arrival_deadline_at is null then null else extract(epoch from(m.arrival_deadline_at-now()))::int end,case when m.called_at is null then 0 when now()>=m.forfeit_at then 4 when now()>=m.penalty_3_at then 3 when now()>=m.penalty_2_at then 2 when now()>=m.penalty_1_at then 1 else 0 end,case when m.called_at is null then 0 when now()>=m.penalty_3_at then 3 when now()>=m.penalty_2_at then 2 when now()>=m.penalty_1_at then 1 else 0 end,(m.forfeit_at is not null and now()>=m.forfeit_at) from public.matches m where m.id=p_match_id $$;

create or replace function public.set_match_ready(p_match_id uuid) returns public.matches language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.matches; pid uuid; begin select tp.id into pid from public.tournament_players tp join public.matches m on m.id=p_match_id and tp.tournament_id=m.tournament_id where tp.user_id=auth.uid() and tp.id in(m.player1_id,m.player2_id); if pid is null then raise exception 'Player is not assigned to this match'; end if; update public.matches set player1_ready_at=case when player1_id=pid then coalesce(player1_ready_at,now()) else player1_ready_at end,player2_ready_at=case when player2_id=pid then coalesce(player2_ready_at,now()) else player2_ready_at end,status=case when (player1_id=pid or player1_ready_at is not null) and (player2_id=pid or player2_ready_at is not null) and status in('pending','waiting_for_table') then 'ready' else status end where id=p_match_id returning * into r; return r; end $$;

create or replace function public.forfeit_match(p_match_id uuid,p_late_player_id uuid,p_reason text) returns public.matches language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.matches; begin update public.matches m set late_player_id=p_late_player_id,forfeit_reason=p_reason,status='forfeited',completed_at=now(),winner_id=case when player1_id=p_late_player_id then player2_id when player2_id=p_late_player_id then player1_id else null end where id=p_match_id and exists(select 1 from public.tournaments t where t.id=m.tournament_id and (t.owner_id=auth.uid() or public.is_admin(auth.uid()))) returning * into r; if r.id is null or r.winner_id is null then raise exception 'Invalid forfeit request'; end if; insert into public.audit_logs(user_id,entity_type,entity_id,action,metadata) values(auth.uid(),'match',p_match_id,'forfeited',jsonb_build_object('late_player_id',p_late_player_id,'reason',p_reason)); return r; end $$;

create or replace function public.propagate_match_result() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ declare loser uuid; begin if new.status in('completed','forfeited') and new.winner_id is not null and (old.status is distinct from new.status or old.winner_id is distinct from new.winner_id) then loser:=case when new.player1_id=new.winner_id then new.player2_id else new.player1_id end; if new.next_match_id is not null then update public.matches set player1_id=case when player1_id is null then new.winner_id else player1_id end,player2_id=case when player1_id is not null and player2_id is null then new.winner_id else player2_id end where id=new.next_match_id and new.winner_id not in(coalesce(player1_id,'00000000-0000-0000-0000-000000000000'),coalesce(player2_id,'00000000-0000-0000-0000-000000000000')); end if; if new.loser_next_match_id is not null and loser is not null then update public.matches set player1_id=case when player1_id is null then loser else player1_id end,player2_id=case when player1_id is not null and player2_id is null then loser else player2_id end where id=new.loser_next_match_id and loser not in(coalesce(player1_id,'00000000-0000-0000-0000-000000000000'),coalesce(player2_id,'00000000-0000-0000-0000-000000000000')); end if; end if; return new; end $$;
drop trigger if exists matches_propagate_result on public.matches; create trigger matches_propagate_result after update of status,winner_id on public.matches for each row execute function public.propagate_match_result();

create or replace function public.complete_tournament(p_tournament_id uuid,p_results jsonb default null) returns public.tournaments language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.tournaments; item jsonb; begin if not exists(select 1 from public.tournaments where id=p_tournament_id and (owner_id=auth.uid() or public.is_admin(auth.uid()))) then raise exception 'Access denied'; end if; if exists(select 1 from public.matches where tournament_id=p_tournament_id and status not in('completed','forfeited')) then raise exception 'Tournament has unfinished matches'; end if; if p_results is not null then for item in select * from jsonb_array_elements(p_results) loop insert into public.tournament_results(tournament_id,tournament_player_id,user_id,final_position,matches_played,wins,losses,score_for,score_against) select p_tournament_id,(item->>'tournament_player_id')::uuid,tp.user_id,(item->>'final_position')::int,coalesce((item->>'matches_played')::int,0),coalesce((item->>'wins')::int,0),coalesce((item->>'losses')::int,0),coalesce((item->>'score_for')::int,0),coalesce((item->>'score_against')::int,0) from public.tournament_players tp where tp.id=(item->>'tournament_player_id')::uuid on conflict(tournament_id,tournament_player_id) do update set final_position=excluded.final_position,matches_played=excluded.matches_played,wins=excluded.wins,losses=excluded.losses,score_for=excluded.score_for,score_against=excluded.score_against; end loop; end if; update public.tournaments set status='completed',completed_at=now() where id=p_tournament_id returning * into r; insert into public.audit_logs(user_id,entity_type,entity_id,action) values(auth.uid(),'tournament',p_tournament_id,'completed'); return r; end $$;
create or replace function public.archive_tournament(p_tournament_id uuid) returns public.tournaments language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.tournaments; begin update public.tournaments set status='archived',archived_at=now() where id=p_tournament_id and status='completed' and (owner_id=auth.uid() or public.is_admin(auth.uid())) returning * into r; if r.id is null then raise exception 'Completed tournament not found or access denied'; end if; insert into public.audit_logs(user_id,entity_type,entity_id,action) values(auth.uid(),'tournament',p_tournament_id,'archived'); return r; end $$;
